/*
 * If not stated otherwise in this file or this component's LICENSE file the
 * following copyright and licenses apply:
 *
 * Copyright 2025 RDK Management
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @file tests/L1Tests/stubs/iarmmgrs_test_stubs.h
 *
 * Single combined stub header for the iarmmgrs L1 unit-test build.
 *
 * Overview
 * --------
 * All stub content that would otherwise be spread across individual shadow
 * headers lives here.  The individual headers (dsTypes.h, dsError.h,
 * dsDisplay.h, dsAudioConfig.h, dsVideoPortConfig.h, dsRpc.h, dsMgr.h,
 * mfrMgr.h, plat_power.h, rfcapi.h) are generated by the CI workflow as
 * thin wrappers that just include this file, keeping the repository tidy.
 *
 * Include-guard strategy
 * ----------------------
 * Each logical section uses its own guard so that the content is harmless if
 * this header is somehow included more than once via different paths.
 *
 * Sentinel macro
 * --------------
 * DRM_DISPLAY_MODE_LEN is defined at the top of the testframework's
 * devicesettings.h (force-included via -include in AM_CPPFLAGS).  It is used
 * throughout this file as a cheap test for "devicesettings.h is already in
 * scope", preventing duplicate type definitions.
 */

#pragma once

#include <stdint.h>
#include <stdbool.h>

/* =========================================================================
 * dsTypes.h / dsError.h shadows
 *
 * All DS HAL types (dsVideoPortType_t, dsAudioPortType_t, dsError_t, …) are
 * provided by devicesettings.h (force-include).  These sections are
 * intentionally empty — the shadow files exist only to prevent the real HAL
 * sub-headers (dsAVDTypes.h, dsFPDTypes.h, …) from being pulled in and
 * re-defining those types.
 * ======================================================================= */

/* Nothing to define — devicesettings.h has already supplied all DS types. */


/* =========================================================================
 * dsDisplay.h shadow
 *
 * Provides dsGetDisplay() so that dsMgr.c can find the prototype.  The
 * actual implementation is the extern "C" bridge in dsHalMock.h.
 * ======================================================================= */
#ifndef _IARMMGRS_STUB_DSDISPLAY_
#define _IARMMGRS_STUB_DSDISPLAY_

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Obtain the opaque display handle for a video port.
 * Declaration only — definition is the DsHal bridge in dsHalMock.h.
 */
dsError_t dsGetDisplay(dsVideoPortType_t type, int index, intptr_t *handle);

#ifdef __cplusplus
}
#endif

#endif /* _IARMMGRS_STUB_DSDISPLAY_ */


/* =========================================================================
 * dsAudioConfig.h shadow
 *
 * dsAudioTypeConfig_t struct and _dsGetAudioTypeConfigs() declaration.
 * The bridge definition lives in dsHalMock.h (DSHAL_MOCK_DEFINE_BRIDGES).
 * ======================================================================= */
#ifndef _IARMMGRS_STUB_DSAUDIOCONFIG_
#define _IARMMGRS_STUB_DSAUDIOCONFIG_

#ifdef __cplusplus
extern "C" {
#endif

/** Per-port audio-type config.  Only 'typeId' is accessed by dsMgr.c. */
typedef struct _dsAudioTypeConfig_t {
    int typeId; /**< Cast to dsAudioPortType_t by dsMgr.c */
} dsAudioTypeConfig_t;

/** Declaration only — bridged to DsHalMock::dsGetAudioTypeConfigs(). */
dsError_t _dsGetAudioTypeConfigs(int *outConfigSize,
                                 const dsAudioTypeConfig_t **outConfigs);

#ifdef __cplusplus
}
#endif

#endif /* _IARMMGRS_STUB_DSAUDIOCONFIG_ */


/* =========================================================================
 * dsVideoPortConfig.h shadow
 *
 * _dsGetVideoPortResolutions() and _dsGetDefaultResolutionIndex() declarations.
 * Bridge definitions live in dsHalMock.h (DSHAL_MOCK_DEFINE_BRIDGES).
 * ======================================================================= */
#ifndef _IARMMGRS_STUB_DSVIDEOPORTCONFIG_
#define _IARMMGRS_STUB_DSVIDEOPORTCONFIG_

#ifdef __cplusplus
extern "C" {
#endif

/** Declaration only — bridged to DsHalMock::dsGetVideoPortResolutions(). */
dsError_t _dsGetVideoPortResolutions(int                      *outResolutionSize,
                                     dsVideoPortResolution_t **outResolutions);

/** Declaration only — bridged to DsHalMock::dsGetDefaultResolutionIndex(). */
dsError_t _dsGetDefaultResolutionIndex(int *outDefaultIndex);

#ifdef __cplusplus
}
#endif

#endif /* _IARMMGRS_STUB_DSVIDEOPORTCONFIG_ */


/* =========================================================================
 * dsRpc.h stub
 *
 * RPC parameter structs and enums used by dsMgr.c / test_dsMgr.cpp.
 *
 * Types already in devicesettings.h (force-include) are guarded with
 * DRM_DISPLAY_MODE_LEN so they are skipped when that file is in scope.
 * ======================================================================= */
#ifndef _IARMMGRS_STUB_DSRPC_
#define _IARMMGRS_STUB_DSRPC_

/* ---- Sleep mode -------------------------------------------------------- */
/* dsSleepMode_t is defined in devicesettings.h; DRM_DISPLAY_MODE_LEN is a
 * sentinel macro from the top of that file. */
#ifndef DRM_DISPLAY_MODE_LEN
typedef enum _dsSleepMode_t {
    dsHOST_SLEEP_MODE_LIGHT,
    dsHOST_SLEEP_MODE_DEEP,
    dsHOST_SLEEP_MODE_MAX
} dsSleepMode_t;
#endif

/* ---- Video-port RPC param structs ------------------------------------- */
typedef struct _dsVideoPortGetHandleParam_t {
    dsVideoPortType_t type;
    int               index;
    intptr_t          handle;
} dsVideoPortGetHandleParam_t;

typedef struct _dsVideoPortIsDisplayConnectedParam_t {
    intptr_t handle;
    bool     connected;
} dsVideoPortIsDisplayConnectedParam_t;

typedef struct _dsVideoPortIsDisplaySurroundParam_t {
    intptr_t handle;
    bool     surround;
} dsVideoPortIsDisplaySurroundParam_t;

typedef struct _dsVideoPortGetResolutionParam_t {
    intptr_t                handle;
    dsVideoPortResolution_t resolution;
    bool                    toPersist;
} dsVideoPortGetResolutionParam_t;

typedef struct _dsVideoPortSetResolutionParam_t {
    intptr_t                handle;
    dsVideoPortResolution_t resolution;
    bool                    toPersist;
    bool                    forceCompatible; /**< Set by dsMgr.c on resolution change */
} dsVideoPortSetResolutionParam_t;

typedef struct _dsForceDisable4KParam_t {
    intptr_t handle;
    bool     disable;
} dsForceDisable4KParam_t;

/* ---- Video background color — must precede _dsSetBackgroundColorParam_t */
typedef enum _dsVideoBackgroundColor_t {
    dsVIDEO_BGCOLOR_NONE,
    dsVIDEO_BGCOLOR_BLACK,
    dsVIDEO_BGCOLOR_WHITE,
    dsVIDEO_BGCOLOR_MAX
} dsVideoBackgroundColor_t;

typedef struct _dsSetBackgroundColorParam_t {
    intptr_t                 handle;
    dsVideoBackgroundColor_t color;
} dsSetBackgroundColorParam_t;

typedef struct _dsEdidIgnoreParam_t {
    intptr_t handle;
    bool     ignoreEDID; /**< dsMgr.c reads this as ignoreEDID */
} dsEdidIgnoreParam_t;

/* ---- Display / EDID RPC param structs ---------------------------------- */
#ifndef dsEEDID_MAX_DATA_SIZE
#define dsEEDID_MAX_DATA_SIZE 512
#endif

typedef struct _dsEDIData_t {
    unsigned char           productCode[2];
    unsigned char           serialNumber[4];
    unsigned char           weekOfManufacture;
    unsigned char           yearOfManufacture;
    unsigned char           hdmiDeviceType;
    unsigned char           isRepeater;
    unsigned char           physicalAddressA;
    unsigned char           physicalAddressB;
    unsigned char           physicalAddressC;
    unsigned char           physicalAddressD;
    int                     numSupportedResolution;
    dsVideoPortResolution_t suppResolutionList[64];
    char                    monitorName[14];
} dsEDIData_t;

/* Compatibility alias: test code written against an older HAL revision uses
 * numOfSupportedResolution; the canonical field name is numSupportedResolution. */
#ifndef numOfSupportedResolution
#define numOfSupportedResolution numSupportedResolution
#endif

typedef struct _dsDisplayGetEDIDParam_t {
    intptr_t    handle;
    dsEDIData_t edid;
} dsDisplayGetEDIDParam_t;

typedef struct _dsDisplayGetEDIDBytesParam_t {
    intptr_t      handle;
    unsigned char bytes[dsEEDID_MAX_DATA_SIZE];
    int           length;
} dsDisplayGetEDIDBytesParam_t;

/* ---- Audio RPC param structs ------------------------------------------- */
typedef struct _dsAudioGetHandleParam_t {
    dsAudioPortType_t type;
    int               index;
    intptr_t          handle;
} dsAudioGetHandleParam_t;

typedef struct _dsAudioSetStereoModeParam_t {
    intptr_t handle;
    int      mode;
    bool     toPersist;
} dsAudioSetStereoModeParam_t;

typedef struct _dsAudioSetStereoAutoParam_t {
    intptr_t handle;
    bool     autoMode;
} dsAudioSetStereoAutoParam_t;

/* ---- API string macros (subset used by dsMgr.c) ------------------------ */
#ifndef IARM_BUS_DSMGR_API_dsGetVideoPort
#define IARM_BUS_DSMGR_API_dsGetVideoPort              "dsGetVideoPort"
#define IARM_BUS_DSMGR_API_dsIsDisplayConnected         "dsIsDisplayConnected"
#define IARM_BUS_DSMGR_API_dsGetIgnoreEDIDStatus        "dsGetIgnoreEDIDStatus"
#define IARM_BUS_DSMGR_API_dsSetResolution              "dsSetResolution"
#define IARM_BUS_DSMGR_API_dsGetResolution              "dsGetResolution"
#define IARM_BUS_DSMGR_API_dsGetEDID                    "dsGetEDID"
#define IARM_BUS_DSMGR_API_dsGetEDIDBytes               "dsGetEDIDBytes"
#define IARM_BUS_DSMGR_API_dsGetForceDisable4K          "dsGetForceDisable4K"
#define IARM_BUS_DSMGR_API_dsSetBackgroundColor         "dsSetBackgroundColor"
#define IARM_BUS_DSMGR_API_dsGetAudioPort               "dsGetAudioPort"
#define IARM_BUS_DSMGR_API_dsGetStereoMode              "dsGetStereoMode"
#define IARM_BUS_DSMGR_API_dsSetStereoMode              "dsSetStereoMode"
#define IARM_BUS_DSMGR_API_dsSetStereoAuto              "dsSetStereoAuto"
#define IARM_BUS_DSMGR_API_dsGetVideoPortResolutions    "dsGetVideoPortResolutions"
#define IARM_BUS_DSMGR_API_dsGetDefaultResolutionIndex  "dsGetDefaultResolutionIndex"
#define IARM_BUS_DSMGR_API_dsGetAudioTypeConfigs        "dsGetAudioTypeConfigs"
#endif
#ifndef IARM_BUS_DSMGR_API_SetStandbyVideoState
#define IARM_BUS_DSMGR_API_SetStandbyVideoState         "dsSetStandbyVideoState"
#define IARM_BUS_DSMGR_API_GetStandbyVideoState         "dsGetStandbyVideoState"
#endif

#endif /* _IARMMGRS_STUB_DSRPC_ */


/* =========================================================================
 * dsMgr.h stub
 *
 * Lifecycle API declarations, dsAudioPortState_t, and
 * IARM_Bus_DSMgr_EventData_t.  All three are guarded with
 * DRM_DISPLAY_MODE_LEN so they are skipped when devicesettings.h (which
 * also defines them) is already in scope.
 * ======================================================================= */
#ifndef _IARMMGRS_STUB_DSMGR_
#define _IARMMGRS_STUB_DSMGR_

#ifdef __cplusplus
extern "C" {
#endif

IARM_Result_t dsMgr_init(void);
IARM_Result_t dsMgr_term(void);

#ifdef __cplusplus
}
#endif

/* dsAudioPortState_t and IARM_Bus_DSMgr_EventData_t are already defined by
 * devicesettings.h when it is force-included. */
#ifndef DRM_DISPLAY_MODE_LEN

typedef enum _dsAudioPortState {
    dsAUDIOPORT_STATE_UNINITIALIZED,
    dsAUDIOPORT_STATE_INITIALIZED,
    dsAUDIOPORT_STATE_MAX
} dsAudioPortState_t;

typedef struct _DSMgr_EventData_t {
    union {
        struct _RESOLUTION_DATA   { int width; int height; } resn;
        struct _DFC_DATA          { int zoomsettings; } dfc;
        struct _AUDIOMODE_DATA    { int type; int mode; } Audioport;
        struct _HDMI_HPD_DATA     { int event; } hdmi_hpd;
        struct _HDMI_HDCP_DATA    { int hdcpStatus; } hdmi_hdcp;
        struct _HDMI_RXSENSE_DATA { int status; } hdmi_rxsense;
        struct _HDMI_IN_CONNECT_DATA {
            dsHdmiInPort_t port; bool isPortConnected;
        } hdmi_in_connect;
        struct _HDMI_IN_STATUS_DATA {
            dsHdmiInPort_t port; bool isPresented;
        } hdmi_in_status;
        struct _HDMI_IN_SIG_STATUS_DATA {
            dsHdmiInPort_t port; dsHdmiInSignalStatus_t status;
        } hdmi_in_sig_status;
        struct _HDMI_IN_VIDEO_MODE_DATA {
            dsHdmiInPort_t port; dsVideoPortResolution_t resolution;
        } hdmi_in_video_mode;
        struct _COMPOSITE_IN_CONNECT_DATA {
            dsCompositeInPort_t port; bool isPortConnected;
        } composite_in_connect;
        struct _COMPOSITE_IN_STATUS_DATA {
            dsCompositeInPort_t port; bool isPresented;
        } composite_in_status;
        struct _COMPOSITE_IN_SIG_STATUS_DATA {
            dsCompositeInPort_t port; dsCompInSignalStatus_t status;
        } composite_in_sig_status;
        struct _COMPOSITE_IN_VIDEO_MODE_DATA {
            dsCompositeInPort_t port; dsVideoPortResolution_t resolution;
        } composite_in_video_mode;
        struct _FPD_TIME_FORMAT        { dsFPDTimeFormat_t eTimeFormat; } FPDTimeFormat;
        struct _HDCP_PROTOCOL_DATA     { dsHdcpProtocolVersion_t protocolVersion; } HDCPProtocolVersion;
        struct _SLEEP_MODE_DATA        { dsSleepMode_t sleepMode; } sleepModeInfo;
        struct _AUDIO_LEVEL_DATA       { int level; } AudioLevelInfo;
        struct _AUDIO_OUT_CONNECT_DATA {
            dsAudioPortType_t portType; unsigned int uiPortNo; bool isPortConnected;
        } audio_out_connect;
        struct _AUDIO_FORMAT_DATA      { dsAudioFormat_t audioFormat; } AudioFormatInfo;
        struct _LANGUAGE_DATA          { char audioLanguage[MAX_LANGUAGE_LEN]; } AudioLanguageInfo;
        struct _FADER_CONTROL_DATA     { int mixerbalance; } FaderControlInfo;
        struct _ASSOCIATED_AUDIO_MIXING_DATA { bool mixing; } AssociatedAudioMixingInfo;
        struct _VIDEO_FORMAT_DATA      { dsHDRStandard_t videoFormat; } VideoFormatInfo;
        struct _AUDIO_PORTSTATE_DATA   { dsAudioPortState_t audioPortState; } AudioPortStateInfo;
        struct _HDMI_IN_ALLM_MODE_DATA { dsHdmiInPort_t port; bool allm_mode; } hdmi_in_allm_mode;
        struct _HDMI_IN_VRR_MODE_DATA  { dsHdmiInPort_t port; dsVRRType_t vrr_type; } hdmi_in_vrr_mode;
        struct _HDMI_IN_CONTENT_TYPE_DATA {
            dsHdmiInPort_t port; dsAviContentType_t aviContentType;
        } hdmi_in_content_type;
        struct _HDMI_IN_AV_LATENCY     { int audio_output_delay; int video_latency; } hdmi_in_av_latency;
        struct _ATMOS_CAPS_CHANGE      { dsATMOSCapability_t caps; bool status; } AtmosCapsChange;
        struct _DISPLAY_FRAMERATE_CHANGE { char framerate[20]; } DisplayFrameRateChange;
    } data;
} IARM_Bus_DSMgr_EventData_t;

#endif /* DRM_DISPLAY_MODE_LEN */

#endif /* _IARMMGRS_STUB_DSMGR_ */


/* =========================================================================
 * plat_power.h stub
 *
 * Minimal power-state enum used by dsMgrPwrEventListener.h.
 * ======================================================================= */
#ifndef _IARMMGRS_STUB_PLATPOWER_
#define _IARMMGRS_STUB_PLATPOWER_

typedef enum _PWRMgr_PowerState_t {
    PWRMGR_POWERSTATE_OFF                = 0,
    PWRMGR_POWERSTATE_STANDBY            = 1,
    PWRMGR_POWERSTATE_ON                 = 2,
    PWRMGR_POWERSTATE_STANDBY_LightSleep = 3,
    PWRMGR_POWERSTATE_STANDBY_DeepSleep  = 4,
    PWRMGR_POWERSTATE_MAX
} PWRMgr_PowerState_t;

#endif /* _IARMMGRS_STUB_PLATPOWER_ */


/* =========================================================================
 * mfrMgr.h stub
 *
 * MFR manager API macros and non-conflicting types.
 * Conflicting types (ThermalState, ThermalSoCTemp, SetBLPattern,
 * SetBLSplashScreen, FsrFlag) come from Iarm.h (testframework).
 * ======================================================================= */
#ifndef _IARMMGRS_STUB_MFRMGR_
#define _IARMMGRS_STUB_MFRMGR_

#ifdef __cplusplus
extern "C" {
#endif
#include "mfrTypes.h"
#include "mfr_wifi_types.h"
#include "mfr_wifi_api.h"
#ifdef __cplusplus
}
#endif

#ifndef IARM_BUS_MFRLIB_NAME
#define IARM_BUS_MFRLIB_NAME                              "MFRLib"
#endif
#define IARM_BUS_MFRLIB_API_SetBootLoaderPattern          "mfrSetBootloaderPattern"
#define IARM_BUS_MFRLIB_API_GetSecureTime                 "mfrGetSecureTime"
#define IARM_BUS_MFRLIB_API_SetSecureTime                 "mfrSetSecureTime"
#define IARM_BUS_MFRLIB_API_SetFsrFlag                    "mfrSetFSRflag"
#define IARM_BUS_MFRLIB_API_GetFsrFlag                    "mfrGetFSRflag"
#define IARM_BUS_MFRLIB_API_GetTemperature                "mfrGetTemperature"
#define IARM_BUS_MFRLIB_API_SetTemperatureThresholds      "mfrSetTempThresholds"
#define IARM_BUS_MFRLIB_API_GetTemperatureThresholds      "mfrGetTempThresholds"
#define IARM_BUS_MFRLIB_API_SearchCPUClockSpeeds          "mfrDetemineClockSpeeds"
#define IARM_BUS_MFRLIB_API_SetCPUClockSpeed              "mfrSetClockSpeed"
#define IARM_BUS_MFRLIB_API_GetCPUClockSpeed              "mfrGetClockSpeed"
#ifndef IARM_BUS_MFRLIB_API_GetSerializedData
#define IARM_BUS_MFRLIB_API_GetSerializedData             "mfrGetManufacturerData"
#endif
#define IARM_BUS_MFRLIB_API_SetSerializedData             "mfrSetManufacturerData"
#define IARM_BUS_MFRLIB_API_DeletePDRI                    "mfrDeletePDRI"
#define IARM_BUS_MFRLIB_API_ScrubAllBanks                 "scrubAllBanks"
#define IARM_BUS_MFRLIB_API_WriteImage                    "mfrWriteImage"
#define IARM_BUS_MFRLIB_API_WIFI_EraseAllData             "mfrWifiEraseAllData"
#define IARM_BUS_MFRLIB_API_WIFI_Credentials              "mfrWifiCredentials"
#define IARM_BUS_MFRLIB_COMMON_API_WriteImageCb           "WriteImageCb"
#define IARM_BUS_MFRLIB_API_validate_image                "mfrValidateImage"
#define IARM_BUS_MFRLIB_API_GetPreDownloadSize            "mfrGetPreDownloadImageSize"
#define IARM_BUS_MFRLIB_API_MirrorImage                   "mfrMirrorImage"
#define IARM_BUS_MFRLIB_API_SetBlSplashScreen             "mfrSetBlSplashScreen"
#define IARM_BUS_MFRLIB_API_ClearBlSplashScreen           "mfrClearBlSplashScreen"
#define IARM_BUS_MFRLIB_API_SetConfigData                 "mfr_setConfigData"
#define IARM_BUS_MFRLIB_API_GetConfigData                 "mfr_getConfigData"

#define MAX_SERIALIZED_BUF 2048
#define MAX_BUF            255

/* GetSerializedData param — guarded to coexist with Iarm.h's copy */
#ifndef IARM_BUS_MFRLIB_GETSERIALIZEDDATA_DEFINED
#define IARM_BUS_MFRLIB_GETSERIALIZEDDATA_DEFINED
typedef struct _IARM_Bus_MFRLib_GetSerializedData_Param_t {
    mfrSerializedType_t type;
    char                buffer[MAX_SERIALIZED_BUF];
    int                 bufLen;
} IARM_Bus_MFRLib_GetSerializedData_Param_t;
#endif

typedef struct _IARM_Bus_MFRLib_ThermalSoCFreq_Param_t {
    uint32_t cpu_rate_Normal;
    uint32_t cpu_rate_Scaled;
    uint32_t cpu_rate_Minimal;
    uint32_t cpu_clock_speed;
} IARM_Bus_MFRLib_ThermalSoCFreq_Param_t;

typedef struct _IARM_Bus_MFRLib_SetSerializedData_Param_t {
    mfrSerializedType_t type;
    char                buffer[MAX_SERIALIZED_BUF];
    int                 bufLen;
} IARM_Bus_MFRLib_SetSerializedData_Param_t;

typedef struct _IARM_Bus_MFRLib_WriteImage_Param_t {
    char           name[MAX_BUF];
    char           path[MAX_BUF];
    mfrImageType_t type;
    char           callerModuleName[MAX_BUF];
    int            interval;
    char           cbData[MAX_BUF];
} IARM_Bus_MFRLib_WriteImage_Param_t;

typedef struct _IARM_Bus_MFRLib_CommonAPI_WriteImageCb_Param_t {
    mfrUpgradeStatus_t status;
    char               cbData[MAX_BUF];
} IARM_Bus_MFRLib_CommonAPI_WriteImageCb_Param_t;

typedef enum _MfrMgr_EventId_t {
    IARM_BUS_MFRMGR_EVENT_STATUS_UPDATE = 0,
    IARM_BUS_MFRMGR_EVENT_MAX,
} IARM_Bus_MfrMgr_EventId_t;

typedef enum _WifiRequestType {
    WIFI_GET_CREDENTIALS = 0,
    WIFI_SET_CREDENTIALS = 1
} WifiRequestType_t;

typedef struct _IARM_BUS_MFRLIB_API_WIFI_Credentials_Param_t {
    WIFI_DATA         wifiCredentials;
    WifiRequestType_t requestType;
    WIFI_API_RESULT   returnVal;
} IARM_BUS_MFRLIB_API_WIFI_Credentials_Param_t;

typedef unsigned long IARM_Bus_MFRLib_SecureTime_Param;

typedef struct _IARM_Bus_MFRLib_Platformblockdata_Param_t {
    unsigned int blocklist;
} IARM_Bus_MFRLib_Platformblockdata_Param_t;

#endif /* _IARMMGRS_STUB_MFRMGR_ */
